services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/ecert
            - ./docker/nginx/prod:/etc/nginx/conf.d
            - /tmp/acme-challenge:/var/www/certbot
            - /etc/letsencrypt:/etc/nginx/ssl
        ports:
            - 80:80
            - 443:443
        depends_on:
            - app
            - certbot
        container_name: ecert_nginx
        networks:
            - ecert-network

    app:
        container_name: ecert_app
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        image: ecert_app
        environment:
            WWWUSER: '1000'
            APP_KEY: ${APP_KEY}
            APP_NAME: ${APP_NAME}
            APP_ENV: ${APP_ENV}
            APP_URL: ${APP_URL}
            APP_DEBUG: ${APP_DEBUG}
            CONTAINER_ROLE: app
        volumes:
            - ./:/var/www/ecert
        working_dir: /var/www/ecert
        depends_on:
            - mysql
        networks:
            - ecert-network

    mysql:
        container_name: ecert_mysql
        build:
            dockerfile: docker/mysql/Dockerfile
        restart: always
        ports:
            - '3308:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - ecert-network

    certbot:
      image: certbot/certbot
      volumes:
        - /tmp/acme-challenge:/var/www/certbot
        - /etc/letsencrypt:/etc/letsencrypt
      command: certonly --webroot --webroot-path=/ssl --email ermek_ospanov@mail.ru --agree-tos --no-eff-email --force-renewal -d vsestroi.kz -d www.vsestroi.kz
      networks:
        - ecert-network

networks:
    ecert-network:
        driver: bridge

volumes:
    certbot-etc:
    certbot-var:
    mysql_data:
        driver: local
