services:
    nginx:
        container_name: ecert_nginx
        image: nginx:alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/nginx/prod:/etc/nginx/conf.d
            - ./:/var/www/ecert
            - /etc/letsencrypt:/etc/letsencrypt:ro
            - /etc/letsencrypt/live/vsestroi.kz/fullchain.pem:/etc/nginx/ssl/fullchain.pem
            - /etc/letsencrypt/live/vsestroi.kz/privkey.pem:/etc/nginx/ssl/privkey.pem

        networks:
            - ecert-network
        depends_on:
            - app
        command: /bin/sh -c "nginx -g 'daemon off;'"

    app:
        container_name: ecert_app
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        image: ecert_app
        environment:
            WWWUSER: '1000'
            APP_KEY: ${APP_KEY}
            APP_NAME: ${APP_NAME}
            APP_ENV: ${APP_ENV}
            APP_URL: ${APP_URL}
            APP_DEBUG: ${APP_DEBUG}
            CONTAINER_ROLE: app
        volumes:
            - ./:/var/www/ecert
        working_dir: /var/www/ecert
        depends_on:
            - mysql
        networks:
            - ecert-network

    mysql:
        container_name: ecert_mysql
        build:
            dockerfile: docker/mysql/Dockerfile
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - ecert-network

    worker:
        container_name: ecert_queue
        image: ecert_app
        command: php artisan queue:work --sleep=3 --timeout=3600
        environment:
            PHP_MEMORY_LIMIT: 512M
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 512M
        restart: unless-stopped
        volumes:
            - ./:/var/www/ecert
        working_dir: /var/www/ecert
        depends_on:
            - mysql
        networks:
            - ecert-network

networks:
    ecert-network:

volumes:
    mysql_data:
        driver: local
