services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www
            - ./docker/nginx/local:/etc/nginx/conf.d
        ports:
            - 8080:80
        depends_on:
            - app
        container_name: ecert_nginx
        networks:
            - ecert-network

    app:
        container_name: ecert_app
        build:
            context: .
            dockerfile: ./docker/php-fpm/Dockerfile
        image: ecert_app
        environment:
            WWWUSER: '1000'
            APP_KEY: ${APP_KEY}
            APP_NAME: ${APP_NAME}
            APP_ENV: ${APP_ENV}
            APP_URL: ${APP_URL}
            APP_DEBUG: ${APP_DEBUG}
            CONTAINER_ROLE: app
        volumes:
            - ./:/var/www
        working_dir: /var/www
        depends_on:
            - mysql
#        ports:
#            - '8080:8080'
        networks:
            - ecert-network

    mysql:
        container_name: ecert_mysql
        build:
            dockerfile: docker/mysql/Dockerfile
        restart: always
        ports:
            - '${FORWARD_DB_PORT:-3309}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - ecert-network

networks:
    ecert-network:
        driver: bridge

volumes:
    mysql:
        driver: local
